server:
  port: 8081

spring:
  application:
    name: product-service

# DATASOURCE
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${PRODUCT_DB_USER:postgres}
    password: ${PRODUCT_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000

# JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: UTC
    open-in-view: false
    show-sql: true